name: test

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
  push:
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.14t', '3.15t']

    env:
      UV_PYTHON: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v7
    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: false
    - name: Install
      run: |
        uv python install ${{ env.UV_PYTHON }}
        uv venv .venv
        uv sync --group test
    - name: Test
      run: |
        make test

  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.14t', '3.15t']

    env:
      UV_PYTHON: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v7
    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: false
    - name: Install
      run: |
        uv python install ${{ env.UV_PYTHON }}
        uv venv .venv
        uv sync --group test
    - name: Test
      run: |
        make test
